<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Db\EventsSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Events
 *
 * Structure class for relation events.events.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Events extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('events.events')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('start_date', 'date')
            ->addField('end_date', 'date')
            ->addField('max_slots', 'int4')
            ->addField('available_slots', 'int4')
            ;
    }
}
